(define (not x) (if x #f #t))
(and
 (boolean? #t)
 (boolean? #f)
 (not (boolean? 1234))
 (not (boolean? 'a))
 (symbol? 'b)
 (procedure? procedure?)
 (equal? (let ((x 0)) (set! x 1)) (if #f 1))
 (= (car (cons 1 2)) 1.0)
 (char? #\a)
 (null? '())
 (string? "abc")
 (symbol? 'lambda)
 (not (string? '(a b c)))
 (not (string? 1234))
 (pair? `(a . b))
 (not (pair? '()))
 (apply zero? '(0))
 (list? (apply list 'a 'b 'c '(d e f)))
 (= (char->integer #\a) (char->integer (string-ref "abc" 0)))
 (let ((n 10000))
   (= n (string-length (make-string n))))
 (let ((n 1))
    (let* ((n 10000)
           (m n))
        (= n (length (string->list (make-string m #\n)))))
 (letrec ((f (lambda () (cons #t f)))) 
    (and (car (f)) (car ((cdr (f))))))
 (= 3.5 (/ 7.0 2))
 (= 35.0 (/ 7e1 2))))
 
