(symbol? car)
(symbol? 'car)
(symbol? (lambda (x) x))
(symbol? '(lambda (x) x))
(symbol? '()) 
(symbol? '(a))
(symbol? #\x)
(symbol? #f)
(symbol? '(a b c))
(symbol? 3) 

(symbol? "hi")
(symbol? 'hi)
(symbol? #\h)

(symbol? 't) 
(symbol? "t")
(symbol? '(t))
(symbol? #\t)
(symbol? #t)