(string? car)
(string? 'car)
(string? (lambda (x) x))
(string? '(lambda (x) x))
(string? '()) 
(string? '(a))
(string? #\x)
(string? #f)
(string? '(a b c))
(string? 3) 

(string? "hi")
(string? 'hi)
(string? #\h)