(rational? car)
(rational? 'car)
(rational? (lambda (x) x))
(rational? '(lambda (x) x))
(rational? '()) 
(rational? '(a))
(rational? #\x)
(rational? #f)
(rational? '(a b c))

(rational? 3) 
(rational? 1901)
(rational? -2/3)
(rational? -3.0)
(rational? 7.0)
(rational? -2.345)
(rational? 3.2)